set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR 8051)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "sdcc.exe")
set(CMAKE_CXX_COMPILER "")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_EXECUTABLE_SUFFIX ".ihx")

set(CMAKE_C_COMPILE_OBJECT
        "<CMAKE_C_COMPILER> -mmcs51 --std c99 --model-small -c <SOURCE> -o <OBJECT>")

set(CMAKE_C_LINK_EXECUTABLE
        "<CMAKE_C_COMPILER> <OBJECTS> -o <TARGET>.ihx")

if (DEFINED SDCC_EXTRA_FLAGS)
    set(CMAKE_C_FLAGS "${SDCC_EXTRA_FLAGS}")
endif ()
